databases:
  - name: postgres
    ipAllowList: []
    databaseName: bug_resolver_production
    user: bug_resolver

services:
  - type: web
    name: bug_resolver
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false