default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: aamir
  password: aamir
  pool: 5
  port: 5432

development:
  <<: *default
  database: blog_development

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: bug_resolver_production
  username: bug_resolver
  password: <%= ENV['MY_APP_RENDER_DATABASE_PASSWORD'] %>